import {useMemo,useState} from 'react';
const words=[
 {word:'VOZ'},{word:'DOTTIE'},{word:'MONA'},{word:'NANCY'},{word:'KNOTTY'},{word:'BUMPY'},{word:'FOREST'},{word:'KINDNESS'},{word:'CHERRY'},{word:'HAPPY'}
] as const;
function mix(word:string,seed:number){const letters=word.split('').map((letter,index)=>({letter,id:index}));for(let i=letters.length-1;i>0;i--){const j=(seed*(i+3)+i*7)%(i+1);[letters[i],letters[j]]=[letters[j],letters[i]]}if(letters.map(item=>item.letter).join('')===word&&letters.length>2)[letters[0],letters[1]]=[letters[1],letters[0]];return letters}
export function WordScramble(){
 const [round,setRound]=useState(0),[seed,setSeed]=useState(11),[picked,setPicked]=useState<number[]>([]),[score,setScore]=useState(0),[streak,setStreak]=useState(0),[status,setStatus]=useState<'play'|'correct'|'wrong'|'complete'>('play');
 const entry=words[round],letters=useMemo(()=>mix(entry.word,seed),[entry.word,seed]),answer=picked.map(id=>letters.find(item=>item.id===id)?.letter||'').join('');
 const choose=(id:number)=>{if(status==='correct'||status==='complete'||picked.includes(id))return;setPicked(current=>[...current,id]);setStatus('play')};
 const remove=(id:number)=>{if(status==='correct'||status==='complete')return;setPicked(current=>current.filter(value=>value!==id));setStatus('play')};
 const check=()=>{if(answer!==entry.word){setStatus('wrong');setStreak(0);return}setScore(score+100+streak*10);setStreak(value=>value+1);setStatus(round===words.length-1?'complete':'correct')};
 const next=()=>{setRound(value=>value+1);setSeed(value=>value+17);setPicked([]);setStatus('play')};
 const restart=()=>{setRound(0);setSeed(value=>value+31);setPicked([]);setScore(0);setStreak(0);setStatus('play')};
 return <section className="wordGame" aria-labelledby="wordGameTitle"><div className="wordGameStory"><span>Forest activity no. 02</span><h2 id="wordGameTitle">Unscramble the <em>words of the forest.</em></h2><p>Every manuscript word names a forest friend, a feeling, or an idea from the story. Arrange the letters to reveal it.</p><div className="wordGamePicture"><img src="/assets/manuscript/page-06.jpg" alt="Forest friends beneath Cherry Jerry from The Soul of the Forest manuscript"/><b>Words are hiding among the leaves</b></div></div><div className="wordGameBoard"><div className="wordGameTop"><span>Word {round+1} of {words.length}</span><div><b>{score}</b> points</div></div><div className="wordGameProgress" aria-label={`${round+1} of ${words.length} words`}><i style={{width:`${((round+(status==='correct'||status==='complete'?1:0))/words.length)*100}%`}}/></div><div className="wordGamePrompt"><small>Build the hidden word</small><p>Choose the letters in the right order.</p></div><div className="wordAnswer" aria-label={'Your answer: '+(answer||'empty')}>{picked.length===0?<span>Tap a letter to begin</span>:picked.map(id=><button key={id} onClick={()=>remove(id)}>{letters.find(item=>item.id===id)?.letter}</button>)}</div><div className="letterTray">{letters.map(item=><button key={item.id} disabled={picked.includes(item.id)||status==='correct'||status==='complete'} onClick={()=>choose(item.id)}>{item.letter}</button>)}</div>{status==='wrong'&&<p className="wordGameMessage wrong">Almost there. Move the letters and try again.</p>}{status==='correct'&&<p className="wordGameMessage correct">Wonderful! You found <strong>{entry.word}</strong>.</p>}{status==='complete'&&<div className="wordGameComplete"><span>✦ Forest word keeper ✦</span><h3>You found every word!</h3><p>Final score: <b>{score}</b></p></div>}<div className="wordGameActions">{status==='complete'?<button className="wordPrimary" onClick={restart}>Play again</button>:status==='correct'?<button className="wordPrimary" onClick={next}>Next word <b>→</b></button>:<><button className="wordClear" onClick={()=>{setPicked([]);setStatus('play')}} disabled={!picked.length}>Clear</button><button className="wordPrimary" onClick={check} disabled={picked.length!==entry.word.length}>Check word</button></>}</div></div></section>
}