export const host='https://www.vaanisworld.com';
export const cover=host+'/assets/soul-of-the-forest-front-cover.png';
export const pages={
 home:['/','The Soul of the Forest by Vaani Halwasiya | Official Website','Discover The Soul of the Forest by Vaani Halwasiya, a magical illustrated children’s book about feelings, friendship, kindness, family and finding your voice.','website'],
 about:['/about','Vaani Halwasiya | Children’s Book Author','Meet Vaani Halwasiya, author of The Soul of the Forest, and discover how feelings, family, kindness and imagination inspire her children’s stories.','profile'],
 books:['/books','The Soul of the Forest | Book by Vaani Halwasiya','Explore The Soul of the Forest by Vaani Halwasiya, an illustrated children’s story about emotions, kindness, friendship and finding your voice.','book'],
 contact:['/contact','Contact Vaani Halwasiya | Author Enquiries','Contact Vaani Halwasiya’s team about reader messages, school and library visits, children’s events, interviews and collaborations.','website'],
 activity:['/kids-activity','Kids Activities | The Soul of the Forest','Play puzzles and creative children’s activities inspired by The Soul of the Forest, the illustrated book by Vaani Halwasiya.','website'],
} as const;
export const entities=[
 {'@type':'Person','@id':host+'/#author',name:'Vaani Halwasiya',url:host+'/about',jobTitle:'Children’s Book Author',description:'Vaani Halwasiya is the young author of The Soul of the Forest.',image:{'@type':'ImageObject',url:host+'/assets/vaani-author.jpeg'},sameAs:['https://www.facebook.com/profile.php?id=61594459104680','https://www.instagram.com/authorvaani/','https://www.youtube.com/channel/UC53QiDpBbMLY1l9SyibE1Ug','https://x.com/authorvaani','https://www.linkedin.com/in/authorvaani-halwasiya-360889433/']},
 {'@type':'Book','@id':host+'/books#book',name:'The Soul of the Forest',alternateName:'Soul of the Forest',url:host+'/books',description:'An illustrated children’s story about feelings, friendship, kindness, family and finding your voice.',author:{'@id':host+'/#author'},image:{'@type':'ImageObject',url:cover,caption:'The Soul of the Forest by Vaani Halwasiya'},genre:['Children’s literature','Picture book'],inLanguage:'en',audience:{'@type':'PeopleAudience',suggestedMinAge:4,suggestedMaxAge:12},mainEntityOfPage:{'@id':host+'/books#webpage'}},
 {'@type':'Organization','@id':host+'/#organization',name:'Vaani’s World',alternateName:'Vaani Halwasiya',url:host,logo:{'@type':'ImageObject',url:host+'/assets/brand/vaani-logo.png'},sameAs:['https://www.facebook.com/profile.php?id=61594459104680','https://www.instagram.com/authorvaani/','https://www.youtube.com/channel/UC53QiDpBbMLY1l9SyibE1Ug','https://x.com/authorvaani','https://www.linkedin.com/in/authorvaani-halwasiya-360889433/']},
 {'@type':'WebSite','@id':host+'/#website',name:'Vaani’s World',alternateName:['Vaani Halwasiya','The Soul of the Forest'],url:host,publisher:{'@id':host+'/#organization'},inLanguage:'en'},
];