import {useEffect,useRef,useState} from 'react';
import {gsap} from 'gsap'; import {ScrollTrigger} from 'gsap/ScrollTrigger'; import {useGSAP} from '@gsap/react';
import {siteContent as c} from './data/siteContent';
import {PageShell} from './pages/PageShell';
import {CurvedMenu,type MenuItem} from './components/ui/curved-menu';
import {KidsActivityPage} from './pages/KidsActivityPage';
import {ManzilFeature} from './components/ManzilFeature';
import {Author3DCard} from './components/ui/3d-card';
import {CharacterCarousel} from './components/ui/character-carousel';
gsap.registerPlugin(ScrollTrigger,useGSAP);
const frame=(n:number)=>`/assets/hero/frames/ezgif-frame-${String(n).padStart(3,'0')}.jpg`;
const menuNotes=['Enter the enchanted forest','Meet the imagination behind the story','Discover every book and world','Play, create, and learn together','Send a note to Vaani'];
const menuItems:MenuItem[]=c.nav.map(([heading,href],i)=>({heading,href,subheading:menuNotes[i]}));

function Loader({done}:{done:boolean}){const [minimumTimePassed,setMinimumTimePassed]=useState(false);useEffect(()=>{const timer=window.setTimeout(()=>setMinimumTimePassed(true),2500);return()=>window.clearTimeout(timer)},[]);const complete=done&&minimumTimePassed;return <div className={`loader ${complete?'done':''}`} aria-hidden={complete}><div className="loaderLogo"><i/><i/><i/><img src="/assets/brand/vaani-logo.png" alt=""/></div><p>The forest is awakening...</p><span className="loaderBar"/></div>}function Hero({onReady}:{onReady:()=>void}){
 const root=useRef<HTMLElement>(null);
 const [active,setActive]=useState(0);
 useGSAP(()=>{
  if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  ScrollTrigger.create({
   trigger:root.current,
   start:'top top',
   end:'bottom bottom',
   invalidateOnRefresh:true,
   onUpdate:self=>{const next=Math.min(c.heroSlides.length-1,Math.floor(self.progress*c.heroSlides.length));setActive(current=>current===next?current:next)}
  });
 },{scope:root});
 return <section ref={root} id="top" className="scrollStoryHero" aria-label="The Soul of the Forest introduction"><div className="scrollStoryStage"><div className="scrollStoryCopy"><div className="scrollStoryText" key={active}><p className="eyebrow">{c.heroSlides[active].eyebrow}</p><h1>{c.heroSlides[active].title}</h1><p className="scrollStoryDescription">{c.heroSlides[active].subtitle}</p><div className="editorialHeroActions"><a className="editorialHeroPrimary" href="#story">Explore the Forest <span>↗</span></a><a className="editorialHeroSecondary" href="#preview">Discover the Book <span>↗</span></a></div></div><div className="scrollStoryBottom"><span>Scroll to discover the forest ↓</span><div className="scrollStoryProgress" aria-label={'Scene '+(active+1)+' of '+c.heroSlides.length}>{c.heroSlides.map((slide,i)=><i key={slide.src} className={i===active?'active':''}/>)}</div></div></div><div className="scrollStoryVisual">{c.heroSlides.map((slide,i)=><div key={slide.src} className={'scrollStorySlide '+(i===active?'active':'')} aria-hidden={i!==active}><img src={slide.src} alt={i===active?slide.alt:''} loading={i===0?'eager':'lazy'} fetchPriority={i===0?'high':undefined} decoding={"async"} onLoad={i===0?onReady:undefined} onError={i===0?onReady:undefined}/></div>)}<div className="scrollStoryNumber"><span>0{active+1}</span><i/>0{c.heroSlides.length}</div></div></div></section>
}
function SectionTitle({kicker,title}:{kicker:string,title:string}){return <div className="sectionTitle"><span>{kicker}</span><h2>{title}</h2></div>}
function Story(){return <section id="story" className="vaaniStory"><Author3DCard imageUrl="/assets/vaani-author.jpeg" title="Vaani Halwasiya" subtitle="A young voice with a forest full of stories." href="/about"/><div className="vaaniStoryCopy"><p className="vaaniStoryEyebrow">Meet the imagination behind the forest</p><h2>A young storyteller with <em>a forest full of feelings.</em></h2><p className="vaaniStoryLead">Vaani Halwasiya created <i>The Soul of the Forest</i> to help children recognize their feelings and discover what helps them feel like themselves again.</p><p>Dottie’s need for rest, Mona’s playful energy, Knotty’s worry and Voz’s song all reflect different parts of Vaani. Through her forest friends, she makes space for joy, frustration, tiredness and everything in between.</p><p>Her story is rooted in the comfort of family and friendship, and in little things that help: a break, a song, a creative moment or someone who listens.</p><div className="vaaniStorySignature"><span>Every mood belongs here.</span><a href="/about">Read Vaani’s story <b>↗</b></a></div></div></section>}
function Characters(){return <section id="characters" className="forestCharacters forestCharactersCarousel"><div className="forestCharactersHead"><span>Meet the forest</span><h2>Every feeling has a friend.</h2><p>These forest friends carry little pieces of Vaani’s own moods. Explore their stories, one friend at a time.</p></div><CharacterCarousel characters={c.characters}/></section>}
function Preview(){return <section id="preview" className="playInvite" aria-labelledby="playInviteTitle"><div className="playInviteInner"><div className="playInviteCopy"><span className="playInviteEyebrow"><i/> THE FOREST IS READY FOR YOU</span><h2 id="playInviteTitle">Little hands.<br/><em>Big forest</em><br/>adventures.</h2><p>Peek at the picture, spot your forest friends, then piece the magic back together in a playful jigsaw made for curious minds.</p><div className="playInviteSteps" aria-label="How to play"><span><b>01</b> Look closely</span><span><b>02</b> Find the pieces</span><span><b>03</b> Make magic</span></div><a className="playInviteButton" href="/kids-activity">Let's play in the forest <span aria-hidden="true">↗</span></a><small>Three levels · Made for little explorers</small></div><div className="playInviteVisual"><div className="playInviteOrbit" aria-hidden="true"/><div className="playInviteImage"><img loading="lazy" src="/assets/forest-friends-activity-optimized.jpg" alt="Forest friends gathered around a magical tree"/></div><div className="playInviteSticker playInviteStickerTop" aria-hidden="true">✦<span>ready<br/>to play?</span></div><div className="playInviteSticker playInviteStickerBottom" aria-hidden="true">FUN<br/>LIVES<br/>HERE!</div><span className="playInvitePiece playInvitePieceOne" aria-hidden="true"/><span className="playInvitePiece playInvitePieceTwo" aria-hidden="true"/><span className="playInviteSparkle" aria-hidden="true">✳</span></div></div></section>}function Author(){return <section id="author" className="bookFeature"><div className="bookFeatureCopy"><p className="bookEyebrow">The featured story</p><h2>A little voice.<br/><em>A forest full of heart.</em></h2><p className="bookDescription"><i>The Soul of the Forest</i> is a warmly illustrated story about kindness, community, motherhood, and the courage to be heard. Follow Voz and her forest friends into a world where even the smallest voice can make a beautiful difference.</p><blockquote>“A keepsake story for curious minds and kind hearts.”</blockquote><div className="bookDetails"><span><b>Perfect for</b>Young readers & families</span><span><b>Inside</b>A richly illustrated adventure</span></div><a className="bookBuy" href={c.purchaseUrl||'/contact'}>Buy your copy now <b>↗</b></a></div><div className="bookMockupScene"><div className="bookAura" aria-hidden="true"/><div className="bookMockup"><img className="bookMockupImage" loading="lazy" src="/assets/the-soul-of-the-forest-book-3d-optimized.png" alt="The Soul of the Forest illustrated book by Vaani Halwasiya"/></div><p className="bookCaption">A story to read together—and remember.</p></div></section>}
function Faq(){const [open,setOpen]=useState(0);return <section id="faqs" className="faq wrap"><SectionTitle kicker="Curious little minds" title="Questions from the forest"/><div>{c.faqs.map(([q,a],i)=><article key={q}><button aria-expanded={open===i} onClick={()=>setOpen(open===i?-1:i)}><span>{String(i+1).padStart(2,'0')}</span>{q}<b>{open===i?'−':'+'}</b></button><div className={open===i?'open':''}><p>{a}</p></div></article>)}</div></section>}
function Footer(){return <footer className="editorialFooter"><div className="footerTop"><p>Stories beyond the expected</p><h2>The next chapter<br/>starts with a <em>conversation.</em></h2><a href="/contact">Connect with Vaani <b>&rarr;</b></a></div><div className="footerDirectory"><div className="footerIdentity"><img src="/assets/brand/vaani-logo.png" alt="Vaani Halwasiya"/><div className="footerAuthor"><span>About the author</span><h3>Young imagination.<br/>A world full of heart.</h3><p>Vaani Halwasiya is a young author and imaginative storyteller who turns everyday feelings into warm, magical adventures. Through her forest friends, she celebrates kindness, family, creativity, and the courage every child needs to find their own voice.</p><a href="/about">Discover Vaani's story <b>&rarr;</b></a></div><div className="footerSocials" aria-label="Social links"><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" className="fill"/></svg><span>Instagram</span></a><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v6h4v-6h3l1-4h-4V9c0-.7.3-1 1-1Z" className="fill"/></svg><span>Facebook</span></a><a href="https://www.youtube.com/" target="_blank" rel="noreferrer" aria-label="YouTube"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 8s-.2-1.5-.8-2.2C19.4 5 18.5 5 18 5 15.6 4.8 12 4.8 12 4.8s-3.6 0-6 .2c-.5 0-1.4 0-2.2.8C3.2 6.5 3 8 3 8s-.2 1.8-.2 3.5V13c0 1.8.2 3.5.2 3.5s.2 1.5.8 2.2c.8.8 1.9.8 2.4.9 1.7.2 5.8.2 5.8.2s3.6 0 6-.2c.5 0 1.4-.1 2.2-.9.6-.7.8-2.2.8-2.2s.2-1.7.2-3.5v-1.5C21.2 9.8 21 8 21 8Zm-11 7.8V8.9l6 3.5-6 3.4Z" className="fill"/></svg><span>YouTube</span></a></div></div><nav aria-label="Footer navigation"><div><b>Explore</b><a href="/">Home</a><a href="/about">About Vaani</a><a href="/bookshelf">Book shelf</a></div><div><b>Discover</b><a href="/kids-activity">Kids activity</a><a href="#faqs">Questions</a><a href="/contact">Contact</a></div></nav></div><div className="footerWordmark" aria-label="Vaani's World"><span>VAANI'S</span> WORLD</div><div className="foot"><p>� {new Date().getFullYear()} Vaani Halwasiya. All rights reserved.</p><a href="#top">Back to top &uarr;</a><span>Stories rooted in kindness</span></div></footer>}
export default function App(){const [ready,setReady]=useState(false);const path=window.location.pathname.replace(/\/$/,'')||'/';useGSAP(()=>{gsap.utils.toArray<HTMLElement>('.sectionTitle, .characterGrid article').forEach(el=>gsap.from(el,{y:40,opacity:0,duration:.8,scrollTrigger:{trigger:el,start:'top 88%'}}))});if(path==='/kids-activity')return <><CurvedMenu items={menuItems}/><KidsActivityPage/><Footer/></>;if(path!=='/'){const page=path.slice(1) as 'about'|'bookshelf'|'contact';if(['about','bookshelf','contact'].includes(page))return <><CurvedMenu items={menuItems}/><PageShell page={page}/><Footer/></>}return <><a className="skip" href="#story">Skip to content</a><Loader done={ready}/><CurvedMenu items={menuItems}/><main><Hero onReady={()=>setReady(true)}/><Story/><Characters/><ManzilFeature/><Preview/><Author/><Faq/></main><Footer/></>}