import {AnimatePresence,motion} from 'framer-motion';
import {useEffect,useRef,useState} from 'react';

export interface MenuItem{heading:string;href:string;subheading:string}

const slide={initial:{x:'calc(100% + 110px)'},enter:{x:0,transition:{duration:.8,ease:[.76,0,.24,1] as const}},exit:{x:'calc(100% + 110px)',transition:{duration:.65,ease:[.76,0,.24,1] as const}}};

function NavLink({item,index,close}:{item:MenuItem;index:number;close:()=>void}){return <motion.a href={item.href} onClick={close} className="curveLink" initial="idle" whileHover="hover"><span className="curveIndex">{String(index).padStart(2,'0')}</span><span className="curveLinkCopy"><motion.strong variants={{idle:{x:0},hover:{x:12}}}>{item.heading}</motion.strong><small>{item.subheading}</small></span><motion.i variants={{idle:{x:-8,opacity:0},hover:{x:0,opacity:1}}}>↗</motion.i></motion.a>}

function Curve({height}:{height:number}){const initial=`M100 0 L200 0 L200 ${height} L100 ${height} Q-100 ${height/2} 100 0`;const target=`M100 0 L200 0 L200 ${height} L100 ${height} Q100 ${height/2} 100 0`;return <svg className="curveEdge" viewBox={`0 0 200 ${height}`} preserveAspectRatio="none" aria-hidden="true"><motion.path fill="#fff8e8" variants={{initial:{d:initial},enter:{d:target,transition:{duration:1,ease:[.76,0,.24,1]}},exit:{d:initial,transition:{duration:.65,ease:[.76,0,.24,1]}}}} initial="initial" animate="enter" exit="exit"/></svg>}

export function CurvedMenu({items}:{items:MenuItem[]}){const [open,setOpen]=useState(false);const [height,setHeight]=useState(900);const button=useRef<HTMLButtonElement>(null);useEffect(()=>{const resize=()=>setHeight(innerHeight);resize();addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[]);useEffect(()=>{document.body.classList.toggle('menuOpen',open);const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);button.current?.focus()}};addEventListener('keydown',key);return()=>{document.body.classList.remove('menuOpen');removeEventListener('keydown',key)}},[open]);return <><button ref={button} className={`curveToggle ${open?'active':''}`} onClick={()=>setOpen(current=>!current)} aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="curved-navigation"><span/><span/><span/></button><AnimatePresence>{open&&<motion.aside id="curved-navigation" className="curvePanel" variants={slide} initial="initial" animate="enter" exit="exit"><Curve height={height}/><div className="curvePanelInner"><div className="curveTop"><a href="/" onClick={()=>setOpen(false)} aria-label="Vaani Halwasiya home"><img className="curveMenuLogo" src="/assets/brand/vaani-logo.png" alt=""/></a><span>Explore the forest</span></div><nav aria-label="Main navigation">{items.map((item,i)=><NavLink key={item.href} item={item} index={i+1} close={()=>setOpen(false)}/>)}</nav><div className="curveBottom"><p>The Soul of the Forest</p><span>A story of kindness, community, and finding your voice.</span></div></div></motion.aside>}</AnimatePresence></>}
